# Generated by Django 6.1.1 on 2026-09-17 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StayLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_id_verified', models.BooleanField(default=False)),
                ('signature_url', models.URLField(blank=True)),
                ('key_cards_issued', models.PositiveIntegerField(default=1)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_handled', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_handled', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guestprofile')),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_logs', to='properties.property')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stay_log', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stay_logs', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Stay Log',
                'verbose_name_plural': 'Stay Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
