# Generated by Django 6.1.1 on 2026-09-17 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('confirmation_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('DIRECT', 'Direct Website'), ('GUEST_APP', 'Guest Mobile App'), ('WALK_IN', 'Walk-in'), ('PHONE', 'Phone Booking'), ('EMAIL', 'Email Booking'), ('OTA_BOOKING_COM', 'Booking.com'), ('OTA_AGODA', 'Agoda'), ('OTA_EXPEDIA', 'Expedia'), ('CORPORATE', 'Corporate Partner')], default='DIRECT', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment / Guarantee'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_HOUSE', 'In-House'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=32)),
                ('check_in_date', models.DateField(db_index=True)),
                ('check_out_date', models.DateField(db_index=True)),
                ('total_adults', models.PositiveIntegerField(default=1)),
                ('total_children', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('special_requests', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guestprofile')),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_rooms', to='rooms.room')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_rooms', to='reservations.reservation')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='rooms.roomtype')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'status', 'check_in_date'], name='reservation_propert_98fba8_idx'),
        ),
    ]
