# Generated by Django 6.1.1 on 2026-09-17 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('organizations', '0001_initial'),
        ('properties', '0001_initial'),
        ('reservations', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('folio_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SETTLED', 'Settled'), ('SUSPENDED', 'Suspended')], db_index=True, default='OPEN', max_length=32)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='guests.guestprofile')),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='properties.property')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf_url', models.URLField(blank=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.folio')),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.property')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('source', models.CharField(choices=[('ROOM_RATE', 'Room Rate Charge'), ('POS_RESTAURANT', 'Restaurant / Bar POS'), ('ROOM_SERVICE', 'Room Service'), ('SPA', 'Spa Treatment'), ('ACTIVITIES', 'Activities / Tours'), ('LAUNDRY', 'Laundry Service'), ('MINIBAR', 'Minibar Consumption'), ('BANQUET', 'Banquet / Event'), ('DAMAGE', 'Damage Penalty'), ('OTHER', 'Other Amenity')], default='OTHER', max_length=32)),
                ('outlet_code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('ADJUSTED', 'Adjusted'), ('VOIDED', 'Voided'), ('REVERSED', 'Reversed')], db_index=True, default='POSTED', max_length=32)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guestprofile')),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_events', to='properties.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_events', to='billing.folio')),
            ],
            options={
                'verbose_name': 'Charge Event',
                'verbose_name_plural': 'Charge Events',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['folio', 'status'], name='billing_cha_folio_i_c151ea_idx')],
                'unique_together': {('property', 'idempotency_key')},
            },
        ),
    ]
