# Generated by Django 6.1.1 on 2026-09-17 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('id_document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID Card'), ('DRIVING_LICENSE', 'Driving License'), ('OTHER', 'Other')], default='PASSPORT', max_length=32)),
                ('id_document_number', models.CharField(blank=True, max_length=64)),
                ('nationality', models.CharField(blank=True, max_length=64)),
                ('vip_status', models.BooleanField(db_index=True, default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest Profile',
                'verbose_name_plural': 'Guest Profiles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
