# Generated by Django 6.1.1 on 2026-09-17 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExecutiveAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PRESIDENT', 'President'), ('VICE_PRESIDENT', 'Vice President'), ('CEO', 'CEO'), ('OPERATIONS_DIRECTOR', 'Operations Director')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_regions', models.ManyToManyField(blank=True, related_name='assigned_executives', to='corporate.region')),
            ],
            options={
                'verbose_name': 'Executive Assignment',
                'verbose_name_plural': 'Executive Assignments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64)),
                ('organization', models.ForeignKey(help_text='The tenant/organization that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_groups', to='corporate.region')),
            ],
            options={
                'verbose_name': 'Property Group',
                'verbose_name_plural': 'Property Groups',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
