# Generated by Django 6.1.1 on 2026-09-17 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=32)),
                ('base_occupancy', models.PositiveIntegerField(default=2)),
                ('max_occupancy', models.PositiveIntegerField(default=4)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.roomamenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property')),
            ],
            options={
                'ordering': ['base_price'],
                'unique_together': {('property', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=32)),
                ('meal_plan', models.CharField(choices=[('RO', 'Room Only'), ('BB', 'Bed & Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], default='RO', max_length=4)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='rooms.roomtype')),
            ],
            options={
                'unique_together': {('property', 'room_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rooms.rateplan')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('rate_plan', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEANING', 'Cleaning'), ('INSPECTION', 'Inspection'), ('OUT_OF_ORDER', 'Out of Order'), ('MAINTENANCE', 'Maintenance'), ('BLOCKED', 'Blocked')], db_index=True, default='AVAILABLE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='properties.floor')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
                'unique_together': {('property', 'room_number')},
            },
        ),
    ]
